# League of Legends Win/Lose Prediction
Task: Binary Classification (Logistic Regression)

In [1]:
from google.colab import files # 파일 업로드
files.upload()

Saving y_test.csv to y_test.csv
Saving x_test.csv to x_test.csv
Saving y_train.csv to y_train.csv
Saving x_train.csv to x_train.csv

In [0]:
import torch
import torch.optim as optim
import torch.nn.functional as F
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler # For Normalization

In [0]:
GPU = torch.cuda.is_available() 
device = torch.device("cuda" if GPU else "cpu") # GPU 사용 가능하면 사용하고 아니면 CPU 사용

In [0]:
torch.manual_seed(777)
torch.cuda.manual_seed_all(777)

## Load Dataset and pre-process

In [0]:
x_train = pd.read_csv('x_train.csv', index_col=0)
y_train = pd.read_csv('y_train.csv', index_col=0)
x_test = pd.read_csv('x_test.csv', index_col=0)
y_test = pd.read_csv('y_test.csv', index_col=0)

In [6]:
x_train.head()

   gameDuraton  blueFirstBlood  ...  Rank_GrandMaster  Rank_Master
0         1713               0  ...                 1            0
1         1577               1  ...                 0            1
2          931               0  ...                 1            0
3         1388               1  ...                 1            0
4         1746               0  ...                 0            0

[5 rows x 48 columns]

In [7]:
y_train.head()

   blueWins
0         1
1         1
2         0
3         1
4         1

In [0]:
x_train = np.array(x_train)
x_test = np.array(x_test)

In [9]:
scaler = MinMaxScaler() # Normalizer
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test) # Not Fit Transform!

pd.DataFrame(x_train).describe()

                  0              1   ...             46             47
count  180000.000000  180000.000000  ...  180000.000000  180000.000000
mean        0.389464       0.506100  ...       0.329461       0.535767
std         0.129449       0.499964  ...       0.470019       0.498720
min         0.000000       0.000000  ...       0.000000       0.000000
25%         0.297216       0.000000  ...       0.000000       0.000000
50%         0.385513       1.000000  ...       0.000000       1.000000
75%         0.478899       1.000000  ...       1.000000       1.000000
max         1.000000       1.000000  ...       1.000000       1.000000

[8 rows x 48 columns]

In [0]:
y_train = np.array(y_train)
y_test = np.array(y_test)

In [0]:
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)
x_test = torch.FloatTensor(x_test)
y_test = torch.FloatTensor(y_test)

## Data Loader

In [0]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [0]:
train_set = TensorDataset(x_train, y_train)

In [0]:
data_loader = DataLoader(dataset=train_set,
                         batch_size=20000,
                         shuffle=True)

## Make Model

In [15]:
print(x_train.shape)
print(y_train.shape)

torch.Size([180000, 48])
torch.Size([180000, 1])

In [16]:
l1 = torch.nn.Linear(48, 16).to(device)
l2 = torch.nn.Linear(16, 1).to(device)
relu = torch.nn.ReLU()
sigmoid = torch.nn.Sigmoid()

model = torch.nn.Sequential(l1, relu, l2, sigmoid)
model

Sequential(
  (0): Linear(in_features=48, out_features=16, bias=True)
  (1): ReLU()
  (2): Linear(in_features=16, out_features=1, bias=True)
  (3): Sigmoid()
)

## Train Model

In [0]:
cost = torch.nn.BCELoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [18]:
epochs = 60
for epoch in range(1, epochs+1):
    avg_cost = 0
    total_batch = len(data_loader)

    for x, y in data_loader:    # batch loop
        x = x.to(device)
        y = y.to(device)

        optimizer.zero_grad()
        hypothesis = model(x)
        cost_val = cost(hypothesis, y)
        cost_val.backward()
        optimizer.step()

        avg_cost += cost_val
    
    avg_cost /= total_batch

    if epoch % 10 == 1 or epoch == epochs:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, epochs, avg_cost.item()))

Epoch    1/60 Cost: 0.679092
Epoch   11/60 Cost: 0.278091
Epoch   21/60 Cost: 0.212358
Epoch   31/60 Cost: 0.181309
Epoch   41/60 Cost: 0.155241
Epoch   51/60 Cost: 0.133555
Epoch   60/60 Cost: 0.118290

## Evaluate Model

In [0]:
with torch.no_grad(): # Don't Calculate Gradient
    x_test = x_test.to(device)

    pred = model(x_test)

In [22]:
pred[pred>=0.5] = 1.0
pred[pred<=0.5] = 0.0
correct_prediction = pred.detach().cpu().float() == y_test
accuracy = correct_prediction.sum().item() / len(correct_prediction)
print('Accuracy {:2.2f}%'.format(accuracy * 100))

Accuracy 96.12%